"""Scientific_name is not unique.

Revision ID: 810aef7bbb1f
Revises: 5f659ace1102
Create Date: 2020-07-18 01:39:22.015731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810aef7bbb1f'
down_revision = '5f659ace1102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plants_scientific_name_key', 'plants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('plants_scientific_name_key', 'plants', ['scientific_name'])
    # ### end Alembic commands ###
